/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (client-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    client.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "client-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Callback routine prototype.  They return the next state.  Normally, that
 *  should be the value of the "maybe_next" argument.
 */
typedef te_client_fsm_state (client_fsm_callback_t)(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt );

static client_fsm_callback_t
    client_fsm_do_closing_connection_connection_closed,
    client_fsm_do_data_sended_response_2xx,
    client_fsm_do_ehlo_sended_response_2xx,
    client_fsm_do_ehlo_sended_response_5xx,
    client_fsm_do_end_data_sended_response_2xx,
    client_fsm_do_hello_sended_response_2xx,
    client_fsm_do_hello_sended_response_502,
    client_fsm_do_hello_sended_response_5xx,
    client_fsm_do_init_response_2xx,
    client_fsm_do_invalid,
    client_fsm_do_mail_sended_response_2xx,
    client_fsm_do_msg_text_sended_response_2xx,
    client_fsm_do_rcpt_sended_response_2xx,
    client_fsm_do_sending_ehlo_ehlo,
    client_fsm_do_sending_hello_hello,
    client_fsm_do_sending_mail_or_quit_mail,
    client_fsm_do_sending_mail_or_quit_quit,
    client_fsm_do_sending_msg_text_or_end_msg_end_data,
    client_fsm_do_sending_rcpt_or_data_data,
    client_fsm_do_sending_rcpt_or_data_rcpt;

/**
 *  Declare all the state transition handling routines.
 */
typedef struct transition t_client_fsm_transition;
struct transition {
    te_client_fsm_state      next_state;
    client_fsm_callback_t *  trans_proc;
};

/**
 *  State transition maps.  Map the enumeration and the event enumeration
 *  to the new state and the transition enumeration code (in that order).
 *  It is indexed by first the current state and then the event code.
 */
static const t_client_fsm_transition
client_fsm_trans_table[ CLIENT_FSM_STATE_CT ][ CLIENT_FSM_EVENT_CT ] = {

  /* STATE 0:  CLIENT_FSM_ST_INIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_SENDING_HELLO, client_fsm_do_init_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 1:  CLIENT_FSM_ST_SENDING_HELLO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_HELLO_SENDED, client_fsm_do_sending_hello_hello }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 2:  CLIENT_FSM_ST_HELLO_SENDED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_hello_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_SENDING_EHLO, client_fsm_do_hello_sended_response_502 }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_CLOSING_CONNECTION, client_fsm_do_hello_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 3:  CLIENT_FSM_ST_SENDING_EHLO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_EHLO_SENDED, client_fsm_do_sending_ehlo_ehlo }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 4:  CLIENT_FSM_ST_EHLO_SENDED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_ehlo_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_CLOSING_CONNECTION, client_fsm_do_ehlo_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 5:  CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_MAIL_SENDED, client_fsm_do_sending_mail_or_quit_mail }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_QUIT_SENDED, client_fsm_do_sending_mail_or_quit_quit } /* EVT:  QUIT */
  },

  /* STATE 6:  CLIENT_FSM_ST_MAIL_SENDED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_SENDING_RCPT_OR_DATA, client_fsm_do_mail_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 7:  CLIENT_FSM_ST_SENDING_RCPT_OR_DATA */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_RCPT_SENDED, client_fsm_do_sending_rcpt_or_data_rcpt }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_DATA_SENDED, client_fsm_do_sending_rcpt_or_data_data }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 8:  CLIENT_FSM_ST_RCPT_SENDED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_SENDING_RCPT_OR_DATA, client_fsm_do_rcpt_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 9:  CLIENT_FSM_ST_DATA_SENDED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_SENDING_MSG_TEXT_OR_END_MSG, client_fsm_do_data_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 10:  CLIENT_FSM_ST_SENDING_MSG_TEXT_OR_END_MSG */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_END_DATA_SENDED, client_fsm_do_sending_msg_text_or_end_msg_end_data }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 11:  CLIENT_FSM_ST_MSG_TEXT_SENDED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_SENDING_MSG_TEXT_OR_END_MSG, client_fsm_do_msg_text_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 12:  CLIENT_FSM_ST_END_DATA_SENDED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_end_data_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 13:  CLIENT_FSM_ST_SENDING_QUIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 14:  CLIENT_FSM_ST_QUIT_SENDED */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 15:  CLIENT_FSM_ST_CLOSING_CONNECTION */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  CONNECTION_CLOSED_BY_SERVER */
    { CLIENT_FSM_ST_DONE, client_fsm_do_closing_connection_connection_closed }, /* EVT:  CONNECTION_CLOSED */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  }
};


#define Client_FsmFsmErr_off     19
#define Client_FsmEvInvalid_off  75
#define Client_FsmStInit_off     83


static char const zClient_FsmStrings[492] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "sending_hello\0"
/*   102 */ "hello_sended\0"
/*   115 */ "sending_ehlo\0"
/*   128 */ "ehlo_sended\0"
/*   140 */ "sending_mail_or_quit\0"
/*   161 */ "mail_sended\0"
/*   173 */ "sending_rcpt_or_data\0"
/*   194 */ "rcpt_sended\0"
/*   206 */ "data_sended\0"
/*   218 */ "sending_msg_text_or_end_msg\0"
/*   246 */ "msg_text_sended\0"
/*   262 */ "end_data_sended\0"
/*   278 */ "sending_quit\0"
/*   291 */ "quit_sended\0"
/*   303 */ "closing_connection\0"
/*   322 */ "none\0"
/*   327 */ "connection_closed_by_server\0"
/*   355 */ "connection_closed\0"
/*   373 */ "response_2xx\0"
/*   386 */ "response_3xx\0"
/*   399 */ "response_4xx\0"
/*   412 */ "response_502\0"
/*   425 */ "response_5xx\0"
/*   438 */ "hello\0"
/*   444 */ "ehlo\0"
/*   449 */ "mail\0"
/*   454 */ "rset\0"
/*   459 */ "rcpt\0"
/*   464 */ "data\0"
/*   469 */ "msg_text\0"
/*   478 */ "end_data\0"
/*   487 */ "quit";

static const size_t aszClient_FsmStates[16] = {
    83,  88,  102, 115, 128, 140, 161, 173, 194, 206, 218, 246, 262, 278, 291,
    303 };

static const size_t aszClient_FsmEvents[18] = {
    322, 327, 355, 373, 386, 399, 412, 425, 438, 444, 449, 454, 459, 464, 469,
    478, 487, 75 };


#define CLIENT_FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 18) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmEvents[t])

#define CLIENT_FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 16) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zClient_FsmStrings + Client_FsmFsmErr_off;
    fprintf( stderr, fmt, st, CLIENT_FSM_STATE_NAME(st), evt, CLIENT_FSM_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

static te_client_fsm_state
client_fsm_do_closing_connection_connection_closed(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == CLOSING CONNECTION CONNECTION CLOSED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == CLOSING CONNECTION CONNECTION CLOSED == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_data_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == DATA SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_ehlo_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == EHLO SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EHLO SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_ehlo_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == EHLO SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EHLO SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_end_data_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == END DATA SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == END DATA SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_hello_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == HELLO SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == HELLO SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_hello_sended_response_502(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == HELLO SENDED RESPONSE 502 == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == HELLO SENDED RESPONSE 502 == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_hello_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == HELLO SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == HELLO SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_init_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INIT RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == INIT RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_invalid(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INVALID == DO NOT CHANGE THIS COMMENT  */
    exit(client_fsm_invalid_transition(initial, trans_evt));
/*  END   == INVALID == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_mail_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MAIL SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MAIL SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_msg_text_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MSG TEXT SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MSG TEXT SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_rcpt_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RCPT SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RCPT SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_ehlo_ehlo(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING EHLO EHLO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING EHLO EHLO == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_hello_hello(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING HELLO HELLO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING HELLO HELLO == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_mail_or_quit_mail(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MAIL OR QUIT MAIL == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MAIL OR QUIT MAIL == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_mail_or_quit_quit(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MAIL OR QUIT QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MAIL OR QUIT QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_msg_text_or_end_msg_end_data(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MSG TEXT OR END MSG END DATA == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MSG TEXT OR END MSG END DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_rcpt_or_data_data(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING RCPT OR DATA DATA == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING RCPT OR DATA DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_rcpt_or_data_rcpt(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING RCPT OR DATA RCPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING RCPT OR DATA RCPT == DO NOT CHANGE THIS COMMENT  */
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  CLIENT_FSM_ST_DONE or CLIENT_FSM_ST_INVALID, it resets to
 *  CLIENT_FSM_ST_INIT and returns CLIENT_FSM_ST_INIT.
 */
te_client_fsm_state
client_fsm_step(
    te_client_fsm_state client_fsm_state,
    te_client_fsm_event trans_evt )
{
    te_client_fsm_state nxtSt;
    client_fsm_callback_t * pT;

    if ((unsigned)client_fsm_state >= CLIENT_FSM_ST_INVALID) {
        return CLIENT_FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= CLIENT_FSM_EV_INVALID) {
        nxtSt = CLIENT_FSM_ST_INVALID;
        pT    = client_fsm_do_invalid;
    } else
#endif /* __COVERITY__ */
    {
        const t_client_fsm_transition * ttbl =
            client_fsm_trans_table[ client_fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        pT    = ttbl->trans_proc;
    }

    if (pT != NULL)
        nxtSt = (*pT)( client_fsm_state, nxtSt, trans_evt );


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of client-fsm.c */
