/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (client-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    client.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2016 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "client-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Callback routine prototype.  They return the next state.  Normally, that
 *  should be the value of the "maybe_next" argument.
 */
typedef te_client_fsm_state (client_fsm_callback_t)(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt );

static client_fsm_callback_t
    client_fsm_do_CLOSED_CONNECTION_close_connection,
    client_fsm_do_DATA_SENDED_close_connection,
    client_fsm_do_EHLO_SENDED_close_connection,
    client_fsm_do_END_DATA_SENDED_close_connection,
    client_fsm_do_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT_close_connection,
    client_fsm_do_HELLO_SENDED_close_connection,
    client_fsm_do_INIT_close_connection,
    client_fsm_do_MAIL_SENDED_close_connection,
    client_fsm_do_MSG_TEXT_SENDED_close_connection,
    client_fsm_do_QUIT_SENDED_close_connection,
    client_fsm_do_RCPT_SENDED_close_connection,
    client_fsm_do_RSET_SENDED_close_connection,
    client_fsm_do_SENDING_EHLO_close_connection,
    client_fsm_do_SENDING_HELLO_close_connection,
    client_fsm_do_SENDING_MAIL_OR_QUIT_close_connection,
    client_fsm_do_SENDING_MSG_TEXT_OR_END_MSG_close_connection,
    client_fsm_do_SENDING_QUIT_close_connection,
    client_fsm_do_SENDING_RCPT_OR_DATA_close_connection,
    client_fsm_do_closed_connection_none,
    client_fsm_do_data_sended_none,
    client_fsm_do_data_sended_response_3xx,
    client_fsm_do_data_sended_response_5xx,
    client_fsm_do_ehlo_sended_none,
    client_fsm_do_ehlo_sended_response_2xx,
    client_fsm_do_ehlo_sended_response_5xx,
    client_fsm_do_end_data_sended_none,
    client_fsm_do_end_data_sended_response_2xx,
    client_fsm_do_end_data_sended_response_4xx,
    client_fsm_do_end_data_sended_response_5xx,
    client_fsm_do_get_next_message_and_sending_mail_or_quit_mail,
    client_fsm_do_get_next_message_and_sending_mail_or_quit_quit,
    client_fsm_do_hello_sended_none,
    client_fsm_do_hello_sended_response_2xx,
    client_fsm_do_hello_sended_response_502,
    client_fsm_do_hello_sended_response_5xx,
    client_fsm_do_init_none,
    client_fsm_do_init_response_2xx,
    client_fsm_do_invalid,
    client_fsm_do_mail_sended_none,
    client_fsm_do_mail_sended_response_2xx,
    client_fsm_do_mail_sended_response_4xx,
    client_fsm_do_mail_sended_response_5xx,
    client_fsm_do_msg_text_sended_none,
    client_fsm_do_quit_sended_none,
    client_fsm_do_quit_sended_response_2xx,
    client_fsm_do_quit_sended_response_4xx,
    client_fsm_do_quit_sended_response_5xx,
    client_fsm_do_rcpt_sended_none,
    client_fsm_do_rcpt_sended_response_2xx,
    client_fsm_do_rcpt_sended_response_4xx,
    client_fsm_do_rcpt_sended_response_5xx,
    client_fsm_do_rset_sended_none,
    client_fsm_do_rset_sended_response_2xx,
    client_fsm_do_sending_ehlo_ehlo,
    client_fsm_do_sending_hello_hello,
    client_fsm_do_sending_mail_or_quit_mail,
    client_fsm_do_sending_mail_or_quit_none,
    client_fsm_do_sending_mail_or_quit_quit,
    client_fsm_do_sending_msg_text_or_end_msg_end_data,
    client_fsm_do_sending_msg_text_or_end_msg_msg_text,
    client_fsm_do_sending_msg_text_or_end_msg_rset,
    client_fsm_do_sending_rcpt_or_data_data,
    client_fsm_do_sending_rcpt_or_data_rcpt,
    client_fsm_do_sending_rcpt_or_data_rset;

/**
 *  Declare all the state transition handling routines.
 */
typedef struct transition t_client_fsm_transition;
struct transition {
    te_client_fsm_state      next_state;
    client_fsm_callback_t *  trans_proc;
};

/**
 *  State transition maps.  Map the enumeration and the event enumeration
 *  to the new state and the transition enumeration code (in that order).
 *  It is indexed by first the current state and then the event code.
 */
static const t_client_fsm_transition
client_fsm_trans_table[ CLIENT_FSM_STATE_CT ][ CLIENT_FSM_EVENT_CT ] = {

  /* STATE 0:  CLIENT_FSM_ST_INIT */
  { { CLIENT_FSM_ST_INIT, client_fsm_do_init_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_INIT_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_SENDING_EHLO, client_fsm_do_init_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 1:  CLIENT_FSM_ST_SENDING_HELLO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_SENDING_HELLO_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_HELLO_SENDED, client_fsm_do_sending_hello_hello }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 2:  CLIENT_FSM_ST_HELLO_SENDED */
  { { CLIENT_FSM_ST_HELLO_SENDED, client_fsm_do_hello_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_HELLO_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_hello_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_SENDING_EHLO, client_fsm_do_hello_sended_response_502 }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_hello_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 3:  CLIENT_FSM_ST_SENDING_EHLO */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_SENDING_EHLO_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_EHLO_SENDED, client_fsm_do_sending_ehlo_ehlo }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 4:  CLIENT_FSM_ST_EHLO_SENDED */
  { { CLIENT_FSM_ST_EHLO_SENDED, client_fsm_do_ehlo_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_EHLO_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_ehlo_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_ehlo_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 5:  CLIENT_FSM_ST_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_MAIL_SENDED, client_fsm_do_get_next_message_and_sending_mail_or_quit_mail }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_QUIT_SENDED, client_fsm_do_get_next_message_and_sending_mail_or_quit_quit } /* EVT:  QUIT */
  },

  /* STATE 6:  CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT */
  { { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_sending_mail_or_quit_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_SENDING_MAIL_OR_QUIT_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_MAIL_SENDED, client_fsm_do_sending_mail_or_quit_mail }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_QUIT_SENDED, client_fsm_do_sending_mail_or_quit_quit } /* EVT:  QUIT */
  },

  /* STATE 7:  CLIENT_FSM_ST_MAIL_SENDED */
  { { CLIENT_FSM_ST_MAIL_SENDED, client_fsm_do_mail_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_MAIL_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_SENDING_RCPT_OR_DATA, client_fsm_do_mail_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_mail_sended_response_4xx }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT, client_fsm_do_mail_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 8:  CLIENT_FSM_ST_SENDING_RCPT_OR_DATA */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_SENDING_RCPT_OR_DATA_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_RSET_SENDED, client_fsm_do_sending_rcpt_or_data_rset }, /* EVT:  RSET */
    { CLIENT_FSM_ST_RCPT_SENDED, client_fsm_do_sending_rcpt_or_data_rcpt }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_DATA_SENDED, client_fsm_do_sending_rcpt_or_data_data }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 9:  CLIENT_FSM_ST_RCPT_SENDED */
  { { CLIENT_FSM_ST_RCPT_SENDED, client_fsm_do_rcpt_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_RCPT_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_SENDING_RCPT_OR_DATA, client_fsm_do_rcpt_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_rcpt_sended_response_4xx }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT, client_fsm_do_rcpt_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 10:  CLIENT_FSM_ST_DATA_SENDED */
  { { CLIENT_FSM_ST_DATA_SENDED, client_fsm_do_data_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_DATA_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_SENDING_MSG_TEXT_OR_END_MSG, client_fsm_do_data_sended_response_3xx }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT, client_fsm_do_data_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 11:  CLIENT_FSM_ST_RSET_SENDED */
  { { CLIENT_FSM_ST_RSET_SENDED, client_fsm_do_rset_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_RSET_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT, client_fsm_do_rset_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 12:  CLIENT_FSM_ST_SENDING_MSG_TEXT_OR_END_MSG */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_SENDING_MSG_TEXT_OR_END_MSG_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_RSET_SENDED, client_fsm_do_sending_msg_text_or_end_msg_rset }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_MSG_TEXT_SENDED, client_fsm_do_sending_msg_text_or_end_msg_msg_text }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_END_DATA_SENDED, client_fsm_do_sending_msg_text_or_end_msg_end_data }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 13:  CLIENT_FSM_ST_MSG_TEXT_SENDED */
  { { CLIENT_FSM_ST_SENDING_MSG_TEXT_OR_END_MSG, client_fsm_do_msg_text_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_MSG_TEXT_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 14:  CLIENT_FSM_ST_END_DATA_SENDED */
  { { CLIENT_FSM_ST_END_DATA_SENDED, client_fsm_do_end_data_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_END_DATA_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT, client_fsm_do_end_data_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_SENDING_MAIL_OR_QUIT, client_fsm_do_end_data_sended_response_4xx }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT, client_fsm_do_end_data_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 15:  CLIENT_FSM_ST_SENDING_QUIT */
  { { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_SENDING_QUIT_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 16:  CLIENT_FSM_ST_QUIT_SENDED */
  { { CLIENT_FSM_ST_QUIT_SENDED, client_fsm_do_quit_sended_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_QUIT_SENDED_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_quit_sended_response_2xx }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_quit_sended_response_4xx }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_quit_sended_response_5xx }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  },

  /* STATE 17:  CLIENT_FSM_ST_CLOSED_CONNECTION */
  { { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_closed_connection_none }, /* EVT:  NONE */
    { CLIENT_FSM_ST_CLOSED_CONNECTION, client_fsm_do_CLOSED_CONNECTION_close_connection }, /* EVT:  CLOSE_CONNECTION */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_2XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_3XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_4XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_502 */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RESPONSE_5XX */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  HELLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  EHLO */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MAIL */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RSET */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  RCPT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  MSG_TEXT */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid }, /* EVT:  END_DATA */
    { CLIENT_FSM_ST_INVALID, client_fsm_do_invalid } /* EVT:  QUIT */
  }
};


#define Client_FsmFsmErr_off     19
#define Client_FsmEvInvalid_off  75
#define Client_FsmStInit_off     83


static char const zClient_FsmStrings[516] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "sending_hello\0"
/*   102 */ "hello_sended\0"
/*   115 */ "sending_ehlo\0"
/*   128 */ "ehlo_sended\0"
/*   140 */ "get_next_message_and_sending_mail_or_quit\0"
/*   182 */ "sending_mail_or_quit\0"
/*   203 */ "mail_sended\0"
/*   215 */ "sending_rcpt_or_data\0"
/*   236 */ "rcpt_sended\0"
/*   248 */ "data_sended\0"
/*   260 */ "rset_sended\0"
/*   272 */ "sending_msg_text_or_end_msg\0"
/*   300 */ "msg_text_sended\0"
/*   316 */ "end_data_sended\0"
/*   332 */ "sending_quit\0"
/*   345 */ "quit_sended\0"
/*   357 */ "closed_connection\0"
/*   375 */ "none\0"
/*   380 */ "close_connection\0"
/*   397 */ "response_2xx\0"
/*   410 */ "response_3xx\0"
/*   423 */ "response_4xx\0"
/*   436 */ "response_502\0"
/*   449 */ "response_5xx\0"
/*   462 */ "hello\0"
/*   468 */ "ehlo\0"
/*   473 */ "mail\0"
/*   478 */ "rset\0"
/*   483 */ "rcpt\0"
/*   488 */ "data\0"
/*   493 */ "msg_text\0"
/*   502 */ "end_data\0"
/*   511 */ "quit";

static const size_t aszClient_FsmStates[18] = {
    83,  88,  102, 115, 128, 140, 182, 203, 215, 236, 248, 260, 272, 300, 316,
    332, 345, 357 };

static const size_t aszClient_FsmEvents[17] = {
    375, 380, 397, 410, 423, 436, 449, 462, 468, 473, 478, 483, 488, 493, 502,
    511, 75 };


#define CLIENT_FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 17) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmEvents[t])

#define CLIENT_FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 18) \
    ? zClient_FsmStrings : zClient_FsmStrings + aszClient_FsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
client_fsm_invalid_transition( te_client_fsm_state st, te_client_fsm_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zClient_FsmStrings + Client_FsmFsmErr_off;
    fprintf( stderr, fmt, st, CLIENT_FSM_STATE_NAME(st), evt, CLIENT_FSM_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

static te_client_fsm_state
client_fsm_do_CLOSED_CONNECTION_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == CLOSED CONNECTION CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == CLOSED CONNECTION CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_DATA_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == DATA SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_EHLO_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == EHLO SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EHLO SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_END_DATA_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == END DATA SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == END DATA SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_GET_NEXT_MESSAGE_AND_SENDING_MAIL_OR_QUIT_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == GET NEXT MESSAGE AND SENDING MAIL OR QUIT CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == GET NEXT MESSAGE AND SENDING MAIL OR QUIT CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_HELLO_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == HELLO SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == HELLO SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_INIT_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INIT CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == INIT CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_MAIL_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MAIL SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MAIL SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_MSG_TEXT_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MSG TEXT SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MSG TEXT SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_QUIT_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == QUIT SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == QUIT SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_RCPT_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RCPT SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RCPT SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_RSET_SENDED_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RSET SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET SENDED CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_SENDING_EHLO_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING EHLO CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING EHLO CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_SENDING_HELLO_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING HELLO CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING HELLO CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_SENDING_MAIL_OR_QUIT_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MAIL OR QUIT CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MAIL OR QUIT CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_SENDING_MSG_TEXT_OR_END_MSG_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MSG TEXT OR END MSG CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MSG TEXT OR END MSG CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_SENDING_QUIT_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING QUIT CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING QUIT CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_SENDING_RCPT_OR_DATA_close_connection(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING RCPT OR DATA CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING RCPT OR DATA CLOSE CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_closed_connection_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == CLOSED CONNECTION NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == CLOSED CONNECTION NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_data_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == DATA SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_data_sended_response_3xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == DATA SENDED RESPONSE 3XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA SENDED RESPONSE 3XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_data_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == DATA SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_ehlo_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == EHLO SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EHLO SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_ehlo_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == EHLO SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EHLO SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_ehlo_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == EHLO SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EHLO SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_end_data_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == END DATA SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == END DATA SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_end_data_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == END DATA SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == END DATA SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_end_data_sended_response_4xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == END DATA SENDED RESPONSE 4XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == END DATA SENDED RESPONSE 4XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_end_data_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == END DATA SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == END DATA SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_get_next_message_and_sending_mail_or_quit_mail(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == GET NEXT MESSAGE AND SENDING MAIL OR QUIT MAIL == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == GET NEXT MESSAGE AND SENDING MAIL OR QUIT MAIL == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_get_next_message_and_sending_mail_or_quit_quit(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == GET NEXT MESSAGE AND SENDING MAIL OR QUIT QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == GET NEXT MESSAGE AND SENDING MAIL OR QUIT QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_hello_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == HELLO SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == HELLO SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_hello_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == HELLO SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == HELLO SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_hello_sended_response_502(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == HELLO SENDED RESPONSE 502 == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == HELLO SENDED RESPONSE 502 == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_hello_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == HELLO SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == HELLO SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_init_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INIT NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == INIT NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_init_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INIT RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == INIT RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_invalid(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == INVALID == DO NOT CHANGE THIS COMMENT  */
    exit(client_fsm_invalid_transition(initial, trans_evt));
/*  END   == INVALID == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_mail_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MAIL SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MAIL SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_mail_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MAIL SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MAIL SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_mail_sended_response_4xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MAIL SENDED RESPONSE 4XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MAIL SENDED RESPONSE 4XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_mail_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MAIL SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MAIL SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_msg_text_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == MSG TEXT SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MSG TEXT SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_quit_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == QUIT SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == QUIT SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_quit_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == QUIT SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == QUIT SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_quit_sended_response_4xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == QUIT SENDED RESPONSE 4XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == QUIT SENDED RESPONSE 4XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_quit_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == QUIT SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == QUIT SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_rcpt_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RCPT SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RCPT SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_rcpt_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RCPT SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RCPT SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_rcpt_sended_response_4xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RCPT SENDED RESPONSE 4XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RCPT SENDED RESPONSE 4XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_rcpt_sended_response_5xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RCPT SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RCPT SENDED RESPONSE 5XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_rset_sended_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RSET SENDED NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET SENDED NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_rset_sended_response_2xx(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == RSET SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET SENDED RESPONSE 2XX == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_ehlo_ehlo(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING EHLO EHLO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING EHLO EHLO == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_hello_hello(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING HELLO HELLO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING HELLO HELLO == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_mail_or_quit_mail(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MAIL OR QUIT MAIL == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MAIL OR QUIT MAIL == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_mail_or_quit_none(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MAIL OR QUIT NONE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MAIL OR QUIT NONE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_mail_or_quit_quit(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MAIL OR QUIT QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MAIL OR QUIT QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_msg_text_or_end_msg_end_data(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MSG TEXT OR END MSG END DATA == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MSG TEXT OR END MSG END DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_msg_text_or_end_msg_msg_text(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MSG TEXT OR END MSG MSG TEXT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MSG TEXT OR END MSG MSG TEXT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_msg_text_or_end_msg_rset(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING MSG TEXT OR END MSG RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING MSG TEXT OR END MSG RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_rcpt_or_data_data(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING RCPT OR DATA DATA == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING RCPT OR DATA DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_rcpt_or_data_rcpt(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING RCPT OR DATA RCPT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING RCPT OR DATA RCPT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_fsm_state
client_fsm_do_sending_rcpt_or_data_rset(
    te_client_fsm_state initial,
    te_client_fsm_state maybe_next,
    te_client_fsm_event trans_evt)
{
/*  START == SENDING RCPT OR DATA RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SENDING RCPT OR DATA RSET == DO NOT CHANGE THIS COMMENT  */
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  CLIENT_FSM_ST_DONE or CLIENT_FSM_ST_INVALID, it resets to
 *  CLIENT_FSM_ST_INIT and returns CLIENT_FSM_ST_INIT.
 */
te_client_fsm_state
client_fsm_step(
    te_client_fsm_state client_fsm_state,
    te_client_fsm_event trans_evt )
{
    te_client_fsm_state nxtSt;
    client_fsm_callback_t * pT;

    if ((unsigned)client_fsm_state >= CLIENT_FSM_ST_INVALID) {
        return CLIENT_FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= CLIENT_FSM_EV_INVALID) {
        nxtSt = CLIENT_FSM_ST_INVALID;
        pT    = client_fsm_do_invalid;
    } else
#endif /* __COVERITY__ */
    {
        const t_client_fsm_transition * ttbl =
            client_fsm_trans_table[ client_fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        pT    = ttbl->trans_proc;
    }

    if (pT != NULL)
        nxtSt = (*pT)( client_fsm_state, nxtSt, trans_evt );


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of client-fsm.c */
