/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (client-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    client.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2018 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "client-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
// clang-format off
#include <string.h>

#include "client.h"
#include "smtp_cmd.h"
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Callback routine prototype.  They return the next state.  Normally, that
 *  should be the value of the "maybe_next" argument.
 */
typedef te_client_state (client_callback_t)(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt );

static client_callback_t
    client_do_CLIENT_INITED_quit,
    client_do_CLIENT_INITED_rset,
    client_do_CLIENT_INITED_shutdown,
    client_do_CLIENT_INITED_timeout,
    client_do_CLIENT_INITED_verify,
    client_do_DATA_RECEIVED_quit,
    client_do_DATA_RECEIVED_rset,
    client_do_DATA_RECEIVED_shutdown,
    client_do_DATA_RECEIVED_timeout,
    client_do_DATA_RECEIVED_verify,
    client_do_EHLO_RECEIVED_quit,
    client_do_EHLO_RECEIVED_rset,
    client_do_EHLO_RECEIVED_shutdown,
    client_do_EHLO_RECEIVED_timeout,
    client_do_EHLO_RECEIVED_verify,
    client_do_END_DATA_RECEIVED_quit,
    client_do_END_DATA_RECEIVED_rset,
    client_do_END_DATA_RECEIVED_shutdown,
    client_do_END_DATA_RECEIVED_timeout,
    client_do_END_DATA_RECEIVED_verify,
    client_do_EXPECTED_MSG_TEXT_OR_END_MSG_quit,
    client_do_EXPECTED_MSG_TEXT_OR_END_MSG_rset,
    client_do_EXPECTED_MSG_TEXT_OR_END_MSG_shutdown,
    client_do_EXPECTED_MSG_TEXT_OR_END_MSG_timeout,
    client_do_EXPECTED_MSG_TEXT_OR_END_MSG_verify,
    client_do_EXPECTED_RCPT_OR_DATA_quit,
    client_do_EXPECTED_RCPT_OR_DATA_rset,
    client_do_EXPECTED_RCPT_OR_DATA_shutdown,
    client_do_EXPECTED_RCPT_OR_DATA_timeout,
    client_do_EXPECTED_RCPT_OR_DATA_verify,
    client_do_HELLO_RECEIVED_quit,
    client_do_HELLO_RECEIVED_rset,
    client_do_HELLO_RECEIVED_shutdown,
    client_do_HELLO_RECEIVED_timeout,
    client_do_HELLO_RECEIVED_verify,
    client_do_INIT_quit,
    client_do_INIT_rset,
    client_do_INIT_shutdown,
    client_do_INIT_timeout,
    client_do_INIT_verify,
    client_do_MAIL_RECEIVED_quit,
    client_do_MAIL_RECEIVED_rset,
    client_do_MAIL_RECEIVED_shutdown,
    client_do_MAIL_RECEIVED_timeout,
    client_do_MAIL_RECEIVED_verify,
    client_do_QUIT_RECEIVED_quit,
    client_do_QUIT_RECEIVED_rset,
    client_do_QUIT_RECEIVED_shutdown,
    client_do_QUIT_RECEIVED_timeout,
    client_do_QUIT_RECEIVED_verify,
    client_do_RCPT_RECEIVED_quit,
    client_do_RCPT_RECEIVED_rset,
    client_do_RCPT_RECEIVED_shutdown,
    client_do_RCPT_RECEIVED_timeout,
    client_do_RCPT_RECEIVED_verify,
    client_do_RSET_RECEIVED_quit,
    client_do_RSET_RECEIVED_rset,
    client_do_RSET_RECEIVED_shutdown,
    client_do_RSET_RECEIVED_timeout,
    client_do_RSET_RECEIVED_verify,
    client_do_UNKNOWN_CMD_RECEIVED_quit,
    client_do_UNKNOWN_CMD_RECEIVED_rset,
    client_do_UNKNOWN_CMD_RECEIVED_shutdown,
    client_do_UNKNOWN_CMD_RECEIVED_timeout,
    client_do_UNKNOWN_CMD_RECEIVED_verify,
    client_do_VERIFY_RECEIVED_quit,
    client_do_VERIFY_RECEIVED_rset,
    client_do_VERIFY_RECEIVED_shutdown,
    client_do_VERIFY_RECEIVED_timeout,
    client_do_VERIFY_RECEIVED_verify,
    client_do_WAIT_HELLO_OR_EHLO_quit,
    client_do_WAIT_HELLO_OR_EHLO_rset,
    client_do_WAIT_HELLO_OR_EHLO_shutdown,
    client_do_WAIT_HELLO_OR_EHLO_timeout,
    client_do_WAIT_HELLO_OR_EHLO_verify,
    client_do_client_inited_mail,
    client_do_data_received_response,
    client_do_ehlo_received_response,
    client_do_end_data_received_response,
    client_do_expected_msg_text_or_end_msg_end_data,
    client_do_expected_msg_text_or_end_msg_msg_text,
    client_do_expected_rcpt_or_data_data,
    client_do_expected_rcpt_or_data_rcpt,
    client_do_hello_received_response,
    client_do_init_response,
    client_do_invalid,
    client_do_mail_received_response,
    client_do_quit_received_response,
    client_do_rcpt_received_response,
    client_do_rset_received_response,
    client_do_verify_received_response,
    client_do_wait_hello_or_ehlo_ehlo,
    client_do_wait_hello_or_ehlo_helo;

/**
 *  Declare all the state transition handling routines.
 */
typedef struct transition t_client_transition;
struct transition {
    te_client_state      next_state;
    client_callback_t *  trans_proc;
};

/**
 *  State transition maps.  Map the enumeration and the event enumeration
 *  to the new state and the transition enumeration code (in that order).
 *  It is indexed by first the current state and then the event code.
 */
static const t_client_transition
client_trans_table[ CLIENT_STATE_CT ][ CLIENT_EVENT_CT ] = {

  /* STATE 0:  CLIENT_ST_INIT */
  { { CLIENT_ST_DONE, client_do_INIT_timeout },     /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_INIT_shutdown },    /* EVT:  SHUTDOWN */
    { CLIENT_ST_WAIT_HELLO_OR_EHLO, client_do_init_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_INIT_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_INIT_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_INIT_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 1:  CLIENT_ST_WAIT_HELLO_OR_EHLO */
  { { CLIENT_ST_DONE, client_do_WAIT_HELLO_OR_EHLO_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_WAIT_HELLO_OR_EHLO_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RESPONSE */
    { CLIENT_ST_EHLO_RECEIVED, client_do_wait_hello_or_ehlo_ehlo }, /* EVT:  EHLO */
    { CLIENT_ST_HELLO_RECEIVED, client_do_wait_hello_or_ehlo_helo }, /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_WAIT_HELLO_OR_EHLO_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_WAIT_HELLO_OR_EHLO_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_WAIT_HELLO_OR_EHLO_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 2:  CLIENT_ST_HELLO_RECEIVED */
  { { CLIENT_ST_DONE, client_do_HELLO_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_HELLO_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_CLIENT_INITED, client_do_hello_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_HELLO_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_HELLO_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_HELLO_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 3:  CLIENT_ST_EHLO_RECEIVED */
  { { CLIENT_ST_DONE, client_do_EHLO_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_EHLO_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_CLIENT_INITED, client_do_ehlo_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_EHLO_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_EHLO_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_EHLO_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 4:  CLIENT_ST_CLIENT_INITED */
  { { CLIENT_ST_DONE, client_do_CLIENT_INITED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_CLIENT_INITED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_MAIL_RECEIVED, client_do_client_inited_mail }, /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_CLIENT_INITED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_CLIENT_INITED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_CLIENT_INITED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 5:  CLIENT_ST_MAIL_RECEIVED */
  { { CLIENT_ST_DONE, client_do_MAIL_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_MAIL_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_EXPECTED_RCPT_OR_DATA, client_do_mail_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_MAIL_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_MAIL_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_MAIL_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 6:  CLIENT_ST_EXPECTED_RCPT_OR_DATA */
  { { CLIENT_ST_DONE, client_do_EXPECTED_RCPT_OR_DATA_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_EXPECTED_RCPT_OR_DATA_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_RCPT_RECEIVED, client_do_expected_rcpt_or_data_rcpt }, /* EVT:  RCPT */
    { CLIENT_ST_DATA_RECEIVED, client_do_expected_rcpt_or_data_data }, /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_EXPECTED_RCPT_OR_DATA_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_EXPECTED_RCPT_OR_DATA_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_EXPECTED_RCPT_OR_DATA_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 7:  CLIENT_ST_RCPT_RECEIVED */
  { { CLIENT_ST_DONE, client_do_RCPT_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_RCPT_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_EXPECTED_RCPT_OR_DATA, client_do_rcpt_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_RCPT_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_RCPT_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_RCPT_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 8:  CLIENT_ST_DATA_RECEIVED */
  { { CLIENT_ST_DONE, client_do_DATA_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_DATA_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_EXPECTED_MSG_TEXT_OR_END_MSG, client_do_data_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_DATA_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_DATA_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_DATA_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 9:  CLIENT_ST_EXPECTED_MSG_TEXT_OR_END_MSG */
  { { CLIENT_ST_DONE, client_do_EXPECTED_MSG_TEXT_OR_END_MSG_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_EXPECTED_MSG_TEXT_OR_END_MSG_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_EXPECTED_MSG_TEXT_OR_END_MSG, client_do_expected_msg_text_or_end_msg_msg_text }, /* EVT:  MSG_TEXT */
    { CLIENT_ST_END_DATA_RECEIVED, client_do_expected_msg_text_or_end_msg_end_data }, /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_EXPECTED_MSG_TEXT_OR_END_MSG_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_EXPECTED_MSG_TEXT_OR_END_MSG_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_EXPECTED_MSG_TEXT_OR_END_MSG_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 10:  CLIENT_ST_END_DATA_RECEIVED */
  { { CLIENT_ST_DONE, client_do_END_DATA_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_END_DATA_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_CLIENT_INITED, client_do_end_data_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_END_DATA_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_END_DATA_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_END_DATA_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 11:  CLIENT_ST_VERIFY_RECEIVED */
  { { CLIENT_ST_DONE, client_do_VERIFY_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_VERIFY_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_CLIENT_INITED, client_do_verify_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_VERIFY_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_VERIFY_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_VERIFY_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 12:  CLIENT_ST_QUIT_RECEIVED */
  { { CLIENT_ST_DONE, client_do_QUIT_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_QUIT_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_DONE, client_do_quit_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_QUIT_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_QUIT_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_QUIT_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 13:  CLIENT_ST_RSET_RECEIVED */
  { { CLIENT_ST_DONE, client_do_RSET_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_RSET_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_CLIENT_INITED, client_do_rset_received_response }, /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_RSET_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_RSET_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_RSET_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  },

  /* STATE 14:  CLIENT_ST_UNKNOWN_CMD_RECEIVED */
  { { CLIENT_ST_DONE, client_do_UNKNOWN_CMD_RECEIVED_timeout }, /* EVT:  TIMEOUT */
    { CLIENT_ST_DONE, client_do_UNKNOWN_CMD_RECEIVED_shutdown }, /* EVT:  SHUTDOWN */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RESPONSE */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  EHLO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  HELO */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MAIL */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  RCPT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  DATA */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  MSG_TEXT */
    { CLIENT_ST_INVALID, client_do_invalid },       /* EVT:  END_DATA */
    { CLIENT_ST_RSET_RECEIVED, client_do_UNKNOWN_CMD_RECEIVED_rset }, /* EVT:  RSET */
    { CLIENT_ST_QUIT_RECEIVED, client_do_UNKNOWN_CMD_RECEIVED_quit }, /* EVT:  QUIT */
    { CLIENT_ST_VERIFY_RECEIVED, client_do_UNKNOWN_CMD_RECEIVED_verify }, /* EVT:  VERIFY */
    { CLIENT_ST_INVALID, client_do_invalid }        /* EVT:  UNKNOWN */
  }
};


#define ClientFsmErr_off     19
#define ClientEvInvalid_off  75
#define ClientStInit_off     83


static char const zClientStrings[420] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "wait_hello_or_ehlo\0"
/*   107 */ "hello_received\0"
/*   122 */ "ehlo_received\0"
/*   136 */ "client_inited\0"
/*   150 */ "mail_received\0"
/*   164 */ "expected_rcpt_or_data\0"
/*   186 */ "rcpt_received\0"
/*   200 */ "data_received\0"
/*   214 */ "expected_msg_text_or_end_msg\0"
/*   243 */ "end_data_received\0"
/*   261 */ "verify_received\0"
/*   277 */ "quit_received\0"
/*   291 */ "rset_received\0"
/*   305 */ "unknown_cmd_received\0"
/*   326 */ "timeout\0"
/*   334 */ "shutdown\0"
/*   343 */ "response\0"
/*   352 */ "ehlo\0"
/*   357 */ "helo\0"
/*   362 */ "mail\0"
/*   367 */ "rcpt\0"
/*   372 */ "data\0"
/*   377 */ "msg_text\0"
/*   386 */ "end_data\0"
/*   395 */ "rset\0"
/*   400 */ "quit\0"
/*   405 */ "verify\0"
/*   412 */ "unknown";

static const size_t aszClientStates[15] = {
    83,  88,  107, 122, 136, 150, 164, 186, 200, 214, 243, 261, 277, 291, 305 };

static const size_t aszClientEvents[15] = {
    326, 334, 343, 352, 357, 362, 367, 372, 377, 386, 395, 400, 405, 412, 75 };


#define CLIENT_EVT_NAME(t)   ( (((unsigned)(t)) >= 15) \
    ? zClientStrings : zClientStrings + aszClientEvents[t])

#define CLIENT_STATE_NAME(s) ( (((unsigned)(s)) >= 15) \
    ? zClientStrings : zClientStrings + aszClientStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int client_invalid_transition( te_client_state st, te_client_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
client_invalid_transition( te_client_state st, te_client_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const* fmt = zClientStrings + ClientFsmErr_off;
    fprintf(stderr, fmt, st, CLIENT_STATE_NAME(st), evt, CLIENT_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

static te_client_state
client_do_CLIENT_INITED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == CLIENT INITED QUIT == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
    client_set_response(client, SMTP_QUIT_SUCCESS_ANSWER, sizeof(SMTP_QUIT_SUCCESS_ANSWER));
    return maybe_next;
    /*  END   == CLIENT INITED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_CLIENT_INITED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == CLIENT INITED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == CLIENT INITED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_CLIENT_INITED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == CLIENT INITED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == CLIENT INITED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_CLIENT_INITED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == CLIENT INITED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == CLIENT INITED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_CLIENT_INITED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == CLIENT INITED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == CLIENT INITED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_DATA_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == DATA RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
    client_set_response(client, SMTP_QUIT_SUCCESS_ANSWER, sizeof(SMTP_QUIT_SUCCESS_ANSWER));
    return maybe_next;
/*  END   == DATA RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_DATA_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == DATA RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_DATA_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == DATA RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_DATA_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == DATA RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_DATA_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == DATA RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EHLO_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EHLO RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
    client_set_response(client, SMTP_QUIT_SUCCESS_ANSWER, sizeof(SMTP_QUIT_SUCCESS_ANSWER));
    return maybe_next;
    /*  END   == EHLO RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EHLO_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EHLO RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == EHLO RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EHLO_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EHLO RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == EHLO RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EHLO_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EHLO RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == EHLO RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EHLO_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EHLO RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == EHLO RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_END_DATA_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == END DATA RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == END DATA RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_END_DATA_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == END DATA RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == END DATA RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_END_DATA_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == END DATA RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == END DATA RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_END_DATA_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == END DATA RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == END DATA RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_END_DATA_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == END DATA RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == END DATA RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_MSG_TEXT_OR_END_MSG_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED MSG TEXT OR END MSG QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EXPECTED MSG TEXT OR END MSG QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_MSG_TEXT_OR_END_MSG_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED MSG TEXT OR END MSG RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EXPECTED MSG TEXT OR END MSG RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_MSG_TEXT_OR_END_MSG_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED MSG TEXT OR END MSG SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EXPECTED MSG TEXT OR END MSG SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_MSG_TEXT_OR_END_MSG_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED MSG TEXT OR END MSG TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EXPECTED MSG TEXT OR END MSG TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_MSG_TEXT_OR_END_MSG_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED MSG TEXT OR END MSG VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EXPECTED MSG TEXT OR END MSG VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_RCPT_OR_DATA_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED RCPT OR DATA QUIT == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
    client_set_response(client, SMTP_QUIT_SUCCESS_ANSWER, sizeof(SMTP_QUIT_SUCCESS_ANSWER));
    return maybe_next;
    /*  END   == EXPECTED RCPT OR DATA QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_RCPT_OR_DATA_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED RCPT OR DATA RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == EXPECTED RCPT OR DATA RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_RCPT_OR_DATA_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED RCPT OR DATA SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == EXPECTED RCPT OR DATA SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_RCPT_OR_DATA_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED RCPT OR DATA TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == EXPECTED RCPT OR DATA TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_EXPECTED_RCPT_OR_DATA_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED RCPT OR DATA VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == EXPECTED RCPT OR DATA VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_HELLO_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == HELLO RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == HELLO RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_HELLO_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == HELLO RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == HELLO RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_HELLO_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == HELLO RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == HELLO RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_HELLO_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == HELLO RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == HELLO RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_HELLO_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == HELLO RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == HELLO RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_INIT_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == INIT QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == INIT QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_INIT_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == INIT RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == INIT RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_INIT_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == INIT SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == INIT SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_INIT_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == INIT TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == INIT TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_INIT_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == INIT VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == INIT VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_MAIL_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == MAIL RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == MAIL RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_MAIL_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == MAIL RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == MAIL RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_MAIL_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == MAIL RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == MAIL RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_MAIL_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == MAIL RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == MAIL RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_MAIL_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == MAIL RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == MAIL RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_QUIT_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == QUIT RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == QUIT RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_QUIT_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == QUIT RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == QUIT RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_QUIT_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == QUIT RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == QUIT RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_QUIT_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == QUIT RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == QUIT RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_QUIT_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == QUIT RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == QUIT RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RCPT_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RCPT RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == RCPT RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RCPT_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RCPT RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == RCPT RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RCPT_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RCPT RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == RCPT RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RCPT_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RCPT RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == RCPT RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RCPT_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RCPT RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == RCPT RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RSET_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RSET RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RSET_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RSET RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RSET_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RSET RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RSET_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RSET RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_RSET_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RSET RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_UNKNOWN_CMD_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == UNKNOWN CMD RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == UNKNOWN CMD RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_UNKNOWN_CMD_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == UNKNOWN CMD RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == UNKNOWN CMD RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_UNKNOWN_CMD_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == UNKNOWN CMD RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == UNKNOWN CMD RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_UNKNOWN_CMD_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == UNKNOWN CMD RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == UNKNOWN CMD RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_UNKNOWN_CMD_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == UNKNOWN CMD RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == UNKNOWN CMD RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_VERIFY_RECEIVED_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == VERIFY RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == VERIFY RECEIVED QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_VERIFY_RECEIVED_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == VERIFY RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == VERIFY RECEIVED RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_VERIFY_RECEIVED_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == VERIFY RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == VERIFY RECEIVED SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_VERIFY_RECEIVED_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == VERIFY RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == VERIFY RECEIVED TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_VERIFY_RECEIVED_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == VERIFY RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == VERIFY RECEIVED VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_WAIT_HELLO_OR_EHLO_quit(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == WAIT HELLO OR EHLO QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == WAIT HELLO OR EHLO QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_WAIT_HELLO_OR_EHLO_rset(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == WAIT HELLO OR EHLO RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == WAIT HELLO OR EHLO RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_WAIT_HELLO_OR_EHLO_shutdown(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == WAIT HELLO OR EHLO SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == WAIT HELLO OR EHLO SHUTDOWN == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_WAIT_HELLO_OR_EHLO_timeout(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == WAIT HELLO OR EHLO TIMEOUT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == WAIT HELLO OR EHLO TIMEOUT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_WAIT_HELLO_OR_EHLO_verify(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == WAIT HELLO OR EHLO VERIFY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == WAIT HELLO OR EHLO VERIFY == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_client_inited_mail(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == CLIENT INITED MAIL == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
    match_info_t* match_info = (match_info_t*)match_info_ptr;
    char buf[1000];
    if (smtp_cmd_get_substring(match_info, MI_MAIL_FROM_REVERSE_PATH_INDEX, buf, sizeof(buf)) == CE_SUCCESS) {
        client_add_mail_from(client, buf, strlen(buf));
    }
    client_set_response(client, SMTP_SUCCESS_ANSWER, sizeof(SMTP_SUCCESS_ANSWER));
    return maybe_next;
    /*  END   == CLIENT INITED MAIL == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_data_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == DATA RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == DATA RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_ehlo_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EHLO RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == EHLO RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_end_data_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == END DATA RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == END DATA RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_expected_msg_text_or_end_msg_end_data(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED MSG TEXT OR END MSG END DATA == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
    match_info_t* match_info = (match_info_t*)match_info_ptr;
    if (match_info->sub_str[0]) {
        client_add_msg_txt(client, match_info->tested_line, match_info->sub_str[0]);
    }
    client_data_end_process(client);
    client_set_response(client, SMTP_SUCCESS_ANSWER, sizeof(SMTP_SUCCESS_ANSWER));
    return maybe_next;
/*  END   == EXPECTED MSG TEXT OR END MSG END DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_expected_msg_text_or_end_msg_msg_text(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED MSG TEXT OR END MSG MSG TEXT == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
    match_info_t* match_info = (match_info_t*)match_info_ptr;
    client_add_msg_txt(client, match_info->tested_line, strlen(match_info->tested_line));
    return maybe_next;
/*  END   == EXPECTED MSG TEXT OR END MSG MSG TEXT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_expected_rcpt_or_data_data(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED RCPT OR DATA DATA == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
     client_set_response(client, SMTP_DATA_ACCEPTED_ANSWER, sizeof(SMTP_DATA_ACCEPTED_ANSWER));
    return maybe_next;
    /*  END   == EXPECTED RCPT OR DATA DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_expected_rcpt_or_data_rcpt(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == EXPECTED RCPT OR DATA RCPT == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
    match_info_t* match_info = (match_info_t*)match_info_ptr;
    client_add_rcpt_to(client, match_info);
    client_set_response(client, SMTP_SUCCESS_ANSWER, sizeof(SMTP_SUCCESS_ANSWER));
    return maybe_next;
    /*  END   == EXPECTED RCPT OR DATA RCPT == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_hello_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == HELLO RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == HELLO RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_init_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == INIT RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == INIT RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_invalid(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == INVALID == DO NOT CHANGE THIS COMMENT  */
    client_invalid_transition(initial, trans_evt);
    return maybe_next;
    /*  END   == INVALID == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_mail_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == MAIL RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == MAIL RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_quit_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == QUIT RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == QUIT RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_rcpt_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RCPT RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
    /*  END   == RCPT RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_rset_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == RSET RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == RSET RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_verify_received_response(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == VERIFY RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == VERIFY RECEIVED RESPONSE == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_wait_hello_or_ehlo_ehlo(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == WAIT HELLO OR EHLO EHLO == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
     match_info_t* match_info = (match_info_t*)match_info_ptr;
    char buf[1000];
    if (smtp_cmd_get_substring(match_info, MI_EHLO_INFO_INDEX, buf, sizeof(buf)) == CE_SUCCESS) {
        client_add_greating_info(client, buf, strlen(buf));
    }
    client_set_response(client, SMTP_SUCCESS_ANSWER, sizeof(SMTP_SUCCESS_ANSWER));
    return maybe_next;
    /*  END   == WAIT HELLO OR EHLO EHLO == DO NOT CHANGE THIS COMMENT  */
}

static te_client_state
client_do_wait_hello_or_ehlo_helo(
    void *client_ptr,
    void *match_info_ptr,
    te_client_state initial,
    te_client_state maybe_next,
    te_client_event trans_evt)
{
/*  START == WAIT HELLO OR EHLO HELO == DO NOT CHANGE THIS COMMENT  */
    client_t* client = (client_t*)client_ptr;
     match_info_t* match_info = (match_info_t*)match_info_ptr;
    char buf[1000];
    if (smtp_cmd_get_substring(match_info, MI_HELO_INFO_INDEX, buf, sizeof(buf)) == CE_SUCCESS) {
        client_add_greating_info(client, buf, strlen(buf));
    }
    client_set_response(client, SMTP_SUCCESS_ANSWER, sizeof(SMTP_SUCCESS_ANSWER));
    return maybe_next;
    /*  END   == WAIT HELLO OR EHLO HELO == DO NOT CHANGE THIS COMMENT  */
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  CLIENT_ST_DONE or CLIENT_ST_INVALID, it resets to
 *  CLIENT_ST_INIT and returns CLIENT_ST_INIT.
 */
te_client_state
client_step(
    te_client_state client_state,
    te_client_event trans_evt,
    void *client_ptr,
    void *match_info_ptr )
{
    te_client_state nxtSt;
    client_callback_t * pT;

    if ((unsigned)client_state >= CLIENT_ST_INVALID) {
        return CLIENT_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= CLIENT_EV_INVALID) {
        nxtSt = CLIENT_ST_INVALID;
        pT    = client_do_invalid;
    } else
#endif /* __COVERITY__ */
    {
        const t_client_transition * ttbl =
            client_trans_table[ client_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        pT    = ttbl->trans_proc;
    }

    if (pT != NULL)
        nxtSt = (*pT)( client_ptr, match_info_ptr, client_state, nxtSt, trans_evt );


    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    // clang-format on
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of client-fsm.c */
